### PR TITLE
Change backend API server's name

### PR DESCRIPTION
**Pull request by dongbohu**

### CODE REVIEW

**Review by vincerubinetti — APPROVED** [review]

**Comment by vincerubinetti** [comment]
Let me try to fix the Netlify preview real quick before we merge this.

**Comment by dongbohu** [comment]
@vincerubinetti Let me know when I can merge it. Thanks.

**Comment by vincerubinetti** [comment]
Can you make a blank commit to hopefully re-trigger the netlify? If it doesn't work right away, we can just merge it and figure out Netlify later.

**Comment by vincerubinetti** [comment]
Okay looks like there was an error but I'm pretty sure I fixed it. If you want to make another empty commit go ahead, or we can just merge.

**Comment by vincerubinetti** [comment]
Good to merge!

**Pull request merged**
