### PR TITLE
Test only: NEVER MERGE

### PR DESCRIPTION
**Pull request by dongbohu**

### CODE REVIEW

**Comment by dongbohu** [comment]
@danich1 and @vincerubinetti: I modified the backend server URL, but I don't know why the netlify web UI doesn't really work:
https://deploy-preview-90--preprint-similarity-search.netlify.app/

But I can get responses with a command like:
```
curl -s "http://35.237.213.166/doi/10.1101/833400"
```

**Comment by vincerubinetti** [comment]
Looks like it's because it's http and not https. I think most browsers now block requests to "insecure" resources.

**Comment by dongbohu** [comment]
That's annoying. I can register a new domain name for the test server and enable HTTPS. But it take a few hours before the new domain name gets effective.

**Comment by vincerubinetti** [comment]
When you're on the preview, you can go to "site settings" in the url bar and allow insecure content. That seems to make the original request process okay, but Sentry seems to throw an error anyway somehow which makes the search fail. Perhaps commenting out all the Sentry lines would fix this.

**Comment by vincerubinetti** [comment]
Looks like it's working!

**Comment by dongbohu** [comment]
I configured HTTPS. I think netlify web UI is working now.

**Comment by dongbohu** [comment]
@danich1, @cgreene and @vincerubinetti: Tell me whether the search results on https://deploy-preview-90--preprint-similarity-search.netlify.app/ make sense or not. Thanks.

**Comment by dongbohu** [comment]
The backend still only includes pre-2020 papers, but is supposed to be more accurate.

**Comment by danich1** [comment]
Can confirm that the search has definitely improved. Tested 10.1101/000026 and the most similar paper is itself.  Also, tested 10.1101/250696 and the top paper can arguable be similar (but not exact match) based on the title.

**Comment by cgreene** [comment]
Yea - these results look pretty reasonable. I think they looked reasonable before too 😂 , but I agree that with better collapsing of similar terms they should be more robust.

**Comment by dongbohu** [comment]
Thank you fro your feedback! I am going to include all new papers that I collected until 04/26/2021 on the test server for you guys to test again. Stay tuned ...

**Pull request closed without merging**
