### PR TITLE
LRU caching for expensive operations

### PR DESCRIPTION
**Pull request by falquaddoomi**
This PR adds LRU caching for `get_doi_neighbors()`, `get_text_neighbors()`, and `get_doi_content()`, all of which appear to be safe to cache for at least as long as the server is running. They would be invalidated by a change in the backing data/model, but the server would need to be restarted to reload those resources anyway, clearing out the cache.

I should state that the current system responds within a reasonable amount of time for what a user would expect, about 2-5 seconds per request. That said, occasionally biorxiv goes down for maintenance for an hour to an hour and a half, and it'd be nice to continue to get results for previously-queried DOIs even when it's down. Also, the similarity search is an expensive operation, but doesn't change without a change in the backing resources. Using an LRU cache brings latency down from the previously-mentioned 2-5 seconds to 5-10 milliseconds.

Again, the caching is a nice-to-have, not a necessity; if there is a chance that the cache will become invalid within the server's running duration, or if it just adds unnecessary complexity, I'm fine with this PR not being merged.

### CODE REVIEW

**Comment by cgreene** [comment]
I agree that these should be safe to cache for as long as the server is running 👍

**Comment by cgreene** [comment]
Oh - wait - would we want to cache only those derived from full text (i.e., not from PDF) because if the PDF gets converted to full text via bioRxiv, we'd want to use the full text instead?

**Comment by cgreene** [comment]
This line would determine whether or not we really want to cache to maintain current behavior:
https://github.com/greenelab/preprint-similarity-search/pull/108/files#diff-971df78691e87978690c6045ec485a4899a76c2f7515e643de91e1100f6b292bR42

I guess the other alternative is that folks upload a new version for their DOI... which we probably also would want to eventually redownload.

I'm guessing LRU doesn't have a way to expire on a weekly basis or something.

**Comment by falquaddoomi** [comment]
@cgreene There is a modified LRU cache that allows you to specify a maximum time-to-live for each record. If a week sounds reasonable, I can modify the cache to store them for just that long.

**Comment by cgreene** [comment]
Nifty!

**Review by danich1 — APPROVED** [review]
LGTM! Will merge now!

**Pull request merged**
