### PR TITLE
add prelim warning

### PR DESCRIPTION
**Pull request by vincerubinetti**
If you want to review the code, please look at the second "reformat" commit and just focus on the first commit diff.

- add "preliminary results" warning for when backend is using PDF instead of XML
- remove greenelab eslint/prettier linting/formatting and reformat everything with create-react-app defaults
- tweak map colors

image

### CODE REVIEW

**Comment by vincerubinetti** [comment]
@dongbohu @cgreene Previously/recently, I've been using [a Greenelab specific/custom eslint and prettier configuration](https://github.com/greenelab/eslint-config-greenelab). But over time, as new rules and tools (like Vue) get added, I've realized it's a fools errand to try to maintain these configurations. As such, going forward, for all Javascript/React/Vue projects, I'll just be using the built-in, default, suggested linting configuration.

**Comment by danich1** [comment]
Will note that tool tip says html. Can this be changed to xml?

**Comment by cgreene** [comment]
bioRxiv calls it Full Text - should we go with that?

**Comment by danich1** [comment]
>bioRxiv calls it Full Text - should we go with that?

Sure let's go with that.

**Comment by danich1** [comment]
One last nitpicking thing. Can we remove "from bioRxiv" in the tooltip as we accept medRxiv preprints as well.

**Review by danich1 — APPROVED** [review]

**Review by dongbohu — APPROVED** [review]

**Pull request merged**
