### PR TITLE
Add cc by, move from popper to simpler tippy library, update packages

### PR DESCRIPTION
**Pull request by vincerubinetti**
- update packages
- add doctype and lang to index.html to fix tooltip position issue and standards compliance
- css tweaks
- add cc by 4.0 to footer
- do font awesome icons by importing individual icons as needed (through fa react package) instead of importing font which includes all fa icons and is 1 mb, to improve loading

### CODE REVIEW

**Review by danich1 — APPROVED** [review]
Is the app preview disabled? Otherwise, the code LGTM!

**Comment by vincerubinetti** [comment]
The preview is here:

image

**Comment by vincerubinetti** [comment]
I noticed that the default preprint `10.1101/833400` is showing up as "preliminary" now. Did the backend flag for that change?

**Comment by danich1** [comment]
>I noticed that the default preprint 10.1101/833400 is showing up as "preliminary" now. Did the backend flag for that change?

For some reason biorxiv is now blocking direct requests to the xml version of their documents. As a consequence our website defaults to pdf versions. Hence the "preliminary results" notification popping up.

**Comment by vincerubinetti** [comment]
@danich1 If that's the case, should we just make the "preliminary" warning note permanent, and stick it in the about section at the bottom?

**Comment by cgreene** [comment]
Richard Sever wasn't aware of a change - I sent him a note. I wouldn't change the behavior until we hear back from upstream.

**Comment by danich1** [comment]
>@danich1 If that's the case, should we just make the "preliminary" warning note permanent, and stick it in the about section at the bottom?

Yeah I think that would be ideal until further notice.

**Pull request merged**
